phases:

  pre_build:

   commands:

       - "echo Logging in to Amazon ECR..."

       - "$(ecs-cli configure --cluster ec2-tutorial --region us-east-1 --default-launch-type EC2 --config-name ec2-tutorial)"

       - "$(ecs-cli configure profile --access-key AKIAIYL5SPAFJWOJCPIQ --secret-key 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 --profile-name  ec2-tutorial)"

  build:

    commands:

      - "$(ecs-cli compose --file docker-compose.yml up --create-log-groups)"

  post_build:

    commands:

      - "echo Logging in to Amazon ECR..."
     
version: 0.2
